---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/public_html/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp -R .env $DEPLOYPATH || true
    - cd $DEPLOYPATH && php artisan optimize:clear || true
    - cd $DEPLOYPATH && php artisan view:clear || true
    - cd $DEPLOYPATH && php artisan config:clear || true
    - cd $DEPLOYPATH && php artisan cache:clear || true
