name: Deploy via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install NPM and Build Assets
        run: |
          npm ci
          npm run build

      - name: Sync App Files to Repositories
        uses: appleboy/ftp-action@master
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          remote_dir: repositories/career-gyan/
          local_dir: ./
          ignore: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/vendor/**
            **/public/**
            .env
            tests/**

      - name: Sync Public Files to Public_HTML
        uses: appleboy/ftp-action@master
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          remote_dir: public_html/
          local_dir: ./public/
          ignore: |
            index.php
            .htaccess
            **/.git*
            **/.git*/**
